# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3907410c006cfc326394836e17ee6c1f0db79c9552d1bce9cab1957636556d8f539f1488e258a3fb3f415d36862bda0e0568832adc4f9e872c0c8860520c072

test:
  secret_key_base: eadaf82b599eff7f7faa1d9909eb8f473a803b5e16499f44c44b510e2d354136fce0bc82c7ee7d0be0804304f47523987c922c0b222b8966e3da583e3b7758cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
